name: Integrate to main branch

on:
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run test