name: Integrate to main branch

on:
  push:
    branches: [ main ]

jobs:
  test_push:
    runs-on: ubuntu-latest
    environment: development
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: |
          touch .env
          echo TEST_MONGODB_URI=${{ secrets.TEST_MONGODB_URI }} >> .env
          echo SECRET=${{ secrets.SECRET }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          cat .env
      - run: npm ci
      - run: npm run test